private "_crate";
_crate = _this;

//_crate addMagazinecargo ["BWA3_DM25", 5];
//_crate addMagazinecargo ["BWA3_DM51A1", 2];
_crate addItemcargo ["Binocular", 1];
_crate addItemcargo ["BWA3_muzzle_snds_G36",1];
_crate addItemcargo ["BWA3_OpsCore_Fleck",1];
_crate addItemcargo ["BWA3_optic_ZO4x30_NSV",1];
_crate addItemcargo ["BWA3_Vest_Grenadier_Fleck",1];
_crate addMagazinecargo ["BWA3_30Rnd_556x45_G36",10];
_crate addMagazinecargo ["Titan_AA", 2];
_crate addMagazinecargo ["Titan_AP", 2];
_crate addMagazinecargo ["Titan_AT", 2];
_crate addWeaponcargo ["BWA3_G36K_equipped", 1];
_crate addWeaponcargo ["BWA3_Pzf3_Loaded",1];
_crate addWeaponcargo ["BWA3_RGW90_Loaded", 1];
_crate addWeaponcargo ["launch_B_Titan_F", 1];
_crate addWeaponcargo ["launch_B_Titan_short_F", 1];
_crate call NTA_fnc_crate_all;