private "_crate";
_crate = _this;
//_crate addMagazinecargo ["BWA3_DM25", 5];
//_crate addMagazinecargo ["BWA3_DM51A1", 2];
_crate addItemcargo ["AGM_SpareBarrel",2];
_crate addItemcargo ["Binocular", 1];
_crate addItemcargo ["BWA3_OpsCore_Fleck",1];
_crate addItemcargo ["BWA3_optic_ZO4x30_NSV",1];
_crate addItemcargo ["BWA3_Vest_Autorifleman_Fleck",1];
_crate addMagazinecargo ["BWA3_120Rnd_762x51",8];
_crate addMagazinecargo ["BWA3_200Rnd_556x45",8];
_crate addWeaponcargo ["BWA3_MG4_equipped", 1];
_crate addWeaponcargo ["BWA3_MG5_equipped",1];
_crate call NTA_fnc_crate_all;